//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int ID { get; set; }
        public string Login1 { get; set; }
        public string Password { get; set; }
        public Nullable<int> idClient { get; set; }
        public Nullable<int> IdEmployee { get; set; }
        public int IdRole { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Role Role { get; set; }
    }
}
