//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VM_ClientGenderCount
    {
        public string Name { get; set; }
        public Nullable<int> Количество_клиентов_ { get; set; }
        public Nullable<decimal> Средний_ценник { get; set; }
    }
}
