//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VM_RoomrentCount
    {
        public short Number { get; set; }
        public string Description { get; set; }
        public Nullable<int> Комната_снималась_раз_ { get; set; }
    }
}
