//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class VM_YearSalaryEmployee
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string ФИО { get; set; }
        public Nullable<decimal> Годовая_зарплата { get; set; }
    }
}
